Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

def puissiter(A,v0,lam,niter,epsilon):
    v = v0
    l = np.dot(v0,np.dot(A,v0))
    ll = [l]
    k=0
    while np.fabs(lam-l)>epsilon and k<niter:
        w = np.dot(A,v)
        v = w/np.linalg.norm(w)
        l = np.dot(v,np.dot(A,v))
        vv.append(v)
        ll.append(l)
        k=k+1
    return ll, vv,k

A = np.array([[2.,1,-1],[1,3,1],[-1,1,4]])
lam =np.max(np.linalg.eigvals(A))
print("La plus grande valeur propre de A est ",lam)

epsilon = 1e-4
niter=50
ll, vv,k = puissiter(A,np.ones(3),lam,niter,epsilon)

plt.figure(figsize=(10,5))
plt.subplot(121)
plt.plot(range(len(ll)),ll,'-o',label='Puissances itÃ©rÃ©es')
plt.plot(range(len(ll)),lam*np.ones((len(ll)), dtype=np.uint8) ,'r')
plt.ylabel('valeur propre')
plt.xlabel('Iteration');
plt.text(0, lam+0.3, "$\lambda$", color="r", fontsize=18)
plt.legend()
plt.title("Valeur propre approchÃ©e Ã  "+ str(epsilon)+" prÃ¨s en "+str(k)+" itÃ©rations")
plt.subplot(122)
plt.plot(range(len(ll)),ll,'-o',label='Puissances itÃ©rÃ©es')
plt.plot(range(len(ll)),lam*np.ones((len(ll)), dtype=np.uint8) ,'r')
plt.ylabel('valeur propre')
plt.xlabel('Iteration');
plt.text(0, lam+0.3, "$\lambda$", color="r", fontsize=18)
plt.legend()
plt.title("Valeur propre approchÃ©e Ã  "+ str(epsilon)+" prÃ¨s en "+str(k)+" itÃ©rations")
plt.tight_layout()



------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<module>[0;34m[0m
[1;32m     22[0m epsilon [38;5;241m=[39m [38;5;241m1e-4[39m
[1;32m     23[0m niter[38;5;241m=[39m[38;5;241m50[39m
[0;32m---> 24[0m ll, vv,k [38;5;241m=[39m [43mpuissiter[49m[43m([49m[43mA[49m[43m,[49m[43mnp[49m[38;5;241;43m.[39;49m[43mones[49m[43m([49m[38;5;241;43m3[39;49m[43m)[49m[43m,[49m[43mlam[49m[43m,[49m[43mniter[49m[43m,[49m[43mepsilon[49m[43m)[49m
[1;32m     26[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m10[39m,[38;5;241m5[39m))
[1;32m     27[0m plt[38;5;241m.[39msubplot([38;5;241m121[39m)

Input [0;32mIn [1][0m, in [0;36mpuissiter[0;34m(A, v0, lam, niter, epsilon)[0m
[1;32m     11[0m v [38;5;241m=[39m w[38;5;241m/[39mnp[38;5;241m.[39mlinalg[38;5;241m.[39mnorm(w)
[1;32m     12[0m l [38;5;241m=[39m np[38;5;241m.[39mdot(v,np[38;5;241m.[39mdot(A,v))
[0;32m---> 13[0m [43mvv[49m[38;5;241m.[39mappend(v)
[1;32m     14[0m ll[38;5;241m.[39mappend(l)
[1;32m     15[0m k[38;5;241m=[39mk[38;5;241m+[39m[38;5;241m1[39m

[0;31mNameError[0m: name 'vv' is not defined
NameError: name 'vv' is not defined

